server:
  port: 8088
spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages
    default-locate : en
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.MySQL8Dialect
      format_sql: true

  data:
    redis:
      #spring.data.redis.use-redis-cache
      use-redis-cache: true
      host: ${REDIS_HOST:localhost} # Default to 'localhost' if not provided
      port: ${REDIS_PORT:6379}      # Default to 6379 if not provided
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    #Phiên bản baseline sẽ = 1 và không thực hiện bất kỳ thay đổi nào trong DB
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: JCyj1zK3npwaFYv65alqdshGiImOQvjAoV7Fr4kHV9k=

logging:
  level:
    org.springframework.security : DEBUG
#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"